//
// Generated file, do not edit! Created by nedtool 5.7 from EthFrames.msg.
//

#ifndef __ETHFRAMES_M_H
#define __ETHFRAMES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>EthFrames.msg:1</tt> by nedtool.
 * <pre>
 * packet EthFrame
 * {
 *     name = "EthFrame";
 *     string dst;
 *     string src;
 *     int ethertype;
 *     byteLength = 26;
 *     simtime_t deadlineA; //priorità
 * 
 *     //int flagSwitch;
 * 
 *     //simtime_t priority; //priorità
 * }
 * </pre>
 */
class EthFrame : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string dst;
    ::omnetpp::opp_string src;
    int ethertype;
    ::omnetpp::simtime_t deadlineA;

  private:
    void copy(const EthFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EthFrame&);

  public:
    EthFrame(const char *name=nullptr, short kind=0);
    EthFrame(const EthFrame& other);
    virtual ~EthFrame();
    EthFrame& operator=(const EthFrame& other);
    virtual EthFrame *dup() const override {return new EthFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDst() const;
    virtual void setDst(const char * dst);
    virtual const char * getSrc() const;
    virtual void setSrc(const char * src);
    virtual int getEthertype() const;
    virtual void setEthertype(int ethertype);
    virtual ::omnetpp::simtime_t getDeadlineA() const;
    virtual void setDeadlineA(::omnetpp::simtime_t deadlineA);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthFrame& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ETHFRAMES_M_H

